// Code generated by jzero. DO NOT EDIT.
// type: fake_{{.Scope}}_client

package fake

import (
	"{{.Module}}/rest"
	"{{$.Module}}/typed/{{.Scope}}"
)

type Fake{{.Scope | FirstUpper}} struct {}

func (f *Fake{{.Scope | FirstUpper}}) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

{{range $v := .Resources}}func (f *Fake{{$.Scope | FirstUpper}}) {{$v | FirstUpper}}() {{$.Scope}}.{{$v | FirstUpper}}Interface {
	return &Fake{{$v | FirstUpper}}{Fake: f}
}

{{end}}