// Code generated by jzero. DO NOT EDIT.
// type: fake_direct_client

package fake

import (
	"github.com/jzero-io/restc"
)

type FakeDirect struct {}

func (f *FakeDirect) RESTClient() restc.Interface {
	var ret *restc.RESTClient
	return ret
}