// Code generated by jzero. DO NOT EDIT.
// type: fake_direct_client

package fake

import (
	"{{.Module}}/rest"
)

type FakeDirect struct {}

func (f *FakeDirect) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}