// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: api/http.proto

package api

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Middleware    string                 `protobuf:"bytes,1,opt,name=middleware,proto3" json:"middleware,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpRule) Reset() {
	*x = HttpRule{}
	mi := &file_api_http_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpRule) ProtoMessage() {}

func (x *HttpRule) ProtoReflect() protoreflect.Message {
	mi := &file_api_http_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpRule.ProtoReflect.Descriptor instead.
func (*HttpRule) Descriptor() ([]byte, []int) {
	return file_api_http_proto_rawDescGZIP(), []int{0}
}

func (x *HttpRule) GetMiddleware() string {
	if x != nil {
		return x.Middleware
	}
	return ""
}

var file_api_http_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpRule)(nil),
		Field:         10000,
		Name:          "jzero.api.http",
		Tag:           "bytes,10000,opt,name=http",
		Filename:      "api/http.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*HttpRule)(nil),
		Field:         10001,
		Name:          "jzero.api.http_group",
		Tag:           "bytes,10001,opt,name=http_group",
		Filename:      "api/http.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional jzero.api.HttpRule http = 10000;
	E_Http = &file_api_http_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional jzero.api.HttpRule http_group = 10001;
	E_HttpGroup = &file_api_http_proto_extTypes[1]
)

var File_api_http_proto protoreflect.FileDescriptor

const file_api_http_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/http.proto\x12\tjzero.api\x1a google/protobuf/descriptor.proto\"*\n" +
	"\bHttpRule\x12\x1e\n" +
	"\n" +
	"middleware\x18\x01 \x01(\tR\n" +
	"middleware:H\n" +
	"\x04http\x12\x1e.google.protobuf.MethodOptions\x18\x90N \x01(\v2\x13.jzero.api.HttpRuleR\x04http:T\n" +
	"\n" +
	"http_group\x12\x1f.google.protobuf.ServiceOptions\x18\x91N \x01(\v2\x13.jzero.api.HttpRuleR\thttpGroupB,Z*github.com/jzero-io/jzero/core/jzeropb/apib\x06proto3"

var (
	file_api_http_proto_rawDescOnce sync.Once
	file_api_http_proto_rawDescData []byte
)

func file_api_http_proto_rawDescGZIP() []byte {
	file_api_http_proto_rawDescOnce.Do(func() {
		file_api_http_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_http_proto_rawDesc), len(file_api_http_proto_rawDesc)))
	})
	return file_api_http_proto_rawDescData
}

var file_api_http_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_http_proto_goTypes = []any{
	(*HttpRule)(nil),                    // 0: jzero.api.HttpRule
	(*descriptorpb.MethodOptions)(nil),  // 1: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
}
var file_api_http_proto_depIdxs = []int32{
	1, // 0: jzero.api.http:extendee -> google.protobuf.MethodOptions
	2, // 1: jzero.api.http_group:extendee -> google.protobuf.ServiceOptions
	0, // 2: jzero.api.http:type_name -> jzero.api.HttpRule
	0, // 3: jzero.api.http_group:type_name -> jzero.api.HttpRule
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_http_proto_init() }
func file_api_http_proto_init() {
	if File_api_http_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_http_proto_rawDesc), len(file_api_http_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_api_http_proto_goTypes,
		DependencyIndexes: file_api_http_proto_depIdxs,
		MessageInfos:      file_api_http_proto_msgTypes,
		ExtensionInfos:    file_api_http_proto_extTypes,
	}.Build()
	File_api_http_proto = out.File
	file_api_http_proto_goTypes = nil
	file_api_http_proto_depIdxs = nil
}
