// Code generated by jzero. DO NOT EDIT.

package daemon

import (
	"github.com/zeromicro/go-zero/core/service"
	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/reflection"

	"{{ .Module }}/daemon/internal/config"
	"{{ .Module }}/daemon/internal/svc"{{ if .ServerImports }}{{ .ServerImports }}{{ end }}{{ if .PbImports }}{{ .PbImports }}{{ end }}
)

func getZrpcServer(c config.Config, ctx *svc.ServiceContext) *zrpc.RpcServer {
	s := zrpc.MustNewServer(c.RpcServerConf, func(grpcServer *grpc.Server) {
	    {{ if .RegisterServers }}{{ .RegisterServers }}{{ end }}

		if c.Mode == service.DevMode || c.Mode == service.TestMode {
			reflection.Register(grpcServer)
		}
	})

	return s
}
