// Code generated by jzero. DO NOT EDIT.

package handler

import (
	"fmt"
	"net/http"
	"strings"
)

var routesCodesMap = map[string]string{
    {{ range $v := .Routes }}"{{ $v.Method | upper }}:{{ $v.Path }}":"{{ replace `/` `:` $v.Group | FirstLower }}:{{ $v.Handler | FirstLower}}",
    {{ end }}
}

func Route2Code(r *http.Request) string {
	path := r.URL.Path
	method := r.Method
	return routesCodesMap[fmt.Sprintf("%s:%s", strings.ToUpper(method), path)]
}
