version: "2"

linters:
  enable:
    - thelper
    - gofumpt
    - tparallel
    - unconvert
    - wastedassign
    - tagliatelle

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jzero-io/jzero