version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - thelper
    - tparallel
    - unconvert
    - unused
    - wastedassign
    - whitespace
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/jzero-io/jzero