{{ if not .Serverless }}// Code generated by jzero. DO NOT EDIT.
package plugins

import (
	"google.golang.org/grpc"

	"{{ .Module }}/internal/svc"
)

func LoadPlugins(grpcServer *grpc.Server, svcCtx *svc.ServiceContext) {}{{end}}