// Code generated by jzero. DO NOT EDIT.
// type: clientset

package {{.APP}}

import (
	"{{.Module}}/rest"
	"{{.Module}}/typed"

	{{range $v := .Scopes}}"{{$.Module}}/typed/{{$v}}"{{end}}
)

type Interface interface {
	Direct() typed.DirectInterface

	{{range $v := .Scopes}}{{$v | FirstUpper}}() {{$v}}.{{$v | FirstUpper}}Interface{{end}}
}

type Clientset struct {
	// direct client to request
	direct *typed.DirectClient

	{{range $v := .Scopes}}{{$v}} *{{$v}}.{{$v | FirstUpper}}Client{{end}}
}

func (x *Clientset) Direct() typed.DirectInterface {
	return x.direct
}

{{range $v := .Scopes}}func (x *Clientset) {{$v | FirstUpper}}() {{$v}}.{{$v | FirstUpper}}Interface {
	return x.{{$v}}
}

{{end}}func NewClientWithOptions(ops ...rest.Opt) ({{if eq (len .Scopes) 1}}{{index .Scopes 0}}.{{index .Scopes 0 | FirstUpper}}Interface{{else}}*Clientset{{end}}, error) {
	c := &rest.RESTClient{}
	for _, op := range ops {
		if err := op(c); err != nil {
			return nil, err
		}
	}
	configShallowCopy := *c
	var cs Clientset
	var err error
	cs.direct, err = typed.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	{{range $v := .Scopes}}cs.{{$v}}, err = {{$v}}.NewForConfig(&configShallowCopy)
	if err != nil {
		return nil, err
	}
	{{end}}
	return {{if eq (len .Scopes) 1}}cs.{{index .Scopes 0 | FirstUpper}}(){{else}}&cs{{end}}, nil
}