// Code generated by jzero. DO NOT EDIT.
package plugins

import (
	"{{ .Module }}/internal/svc"
	"google.golang.org/grpc"

	{{range $v := .Plugins}}{{ $v.Path | base }} "{{ $v.Module }}/serverless"
    {{end}}
)

func LoadPlugins(grpcServer *grpc.Server,svcCtx *svc.ServiceContext) {
    {{ range $v := .Plugins }}
	    {
            serverless := {{ $v.Path | base }}.New()
            serverless.RegisterZrpcServer(grpcServer, serverless.SvcCtx)
            svcCtx.ConfigCenter.MustGetConfig().Gateway.Upstreams[0].ProtoSets = append(svcCtx.ConfigCenter.MustGetConfig().Gateway.Upstreams[0].ProtoSets, serverless.ProtoSets...)
        }
	{{end}}
}

