// Code generated by jzero. DO NOT EDIT.

package mongo

import (
	"github.com/jzero-io/jzero/core/stores/monx"
    "github.com/eddieowens/opts"

	{{range $v := .Imports}}{{$v | base}} "{{$v}}"
	{{end}}
)

{{range $k,$v := .MutiModels}} type {{$k | FirstUpper | ToCamel}}Model struct {
    {{range $vv := $v}}{{$vv | FirstUpper | ToCamel}} {{$vv}}.{{$vv | FirstUpper |ToCamel}}Model
    {{end}}
}
{{end}}

type Model struct {
    {{range $v := .TypePackages}}{{$v | FirstUpper | ToCamel}} {{$v}}.{{$v | FirstUpper |ToCamel}}Model
    {{end}}
}

func NewModel(url, db string, op ...opts.Opt[monx.MonOpts]) Model {
	return Model{
         {{range $v := .TypePackages}}{{$v | FirstUpper | ToCamel}}: {{$v}}.New{{ $v | FirstUpper | ToCamel }}Model(url, db, op...),
         {{end}}
	}
}

{{range $k,$v := .MutiModels}} func New{{$k | FirstUpper | ToCamel}}Model(url, db string, op ...opts.Opt[monx.MonOpts]) {{$k | FirstUpper | ToCamel}}Model {
	return {{$k | FirstUpper | ToCamel}}Model{
        {{range $vv := $v}}{{$vv | FirstUpper | ToCamel}}: {{$vv}}.New{{ $vv | FirstUpper | ToCamel }}Model(url, db, op...),
        {{end}}
	}
}
{{end}}