// Code generated by jzero. DO NOT EDIT.
// type: direct_client

package typed

import (
	"github.com/jzero-io/restc"
)


type DirectInterface interface {
	RESTClient() restc.Interface
}

type DirectClient struct {
	restClient restc.Interface
}

func (x *DirectClient) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

// NewForConfig creates a new DirectClient for the given config.
func NewForConfig(x *restc.RESTClient) (*DirectClient, error) {
	return &DirectClient{x}, nil
}