{{define "methodDefine"}}{{.MethodName}}({{if or .IsStreamServer .IsStreamClient }}{{else}}ctx context.Context,{{end}}{{ .Request.FullName }}) ({{if or .IsStreamServer .IsStreamClient}}*restc.Request{{else}}{{.Response.FullName}}{{end}}, error){{end}}
// Code generated by jzero. DO NOT EDIT.
// type: {{.Resource}}

package {{.Resource | base | lower}}

import (
    "context"

    "github.com/jzero-io/restc"

    {{range $v := .GoImportPaths | uniq}}"{{$v}}"
    {{end}}
)

var (
    _ = context.Background()
)

type {{.Resource | FirstUpper| ToCamel}} interface {
	{{range $k, $v := .HTTPInterfaces}}// {{$v.Method}}:{{$v.URL}} {{.Comments}}
	{{template "methodDefine" $v}}
	{{end}}
}

type {{.Resource | ToCamel | FirstLower}}Client struct {
	client restc.Client
}

func New{{.Resource | ToCamel | FirstUpper}}(c restc.Client) {{.Resource | FirstUpper| ToCamel}} {
	return &{{.Resource | ToCamel | FirstLower}}Client{
		client: c,
	}
}

{{range $k, $v := .HTTPInterfaces}}func (x *{{$.Resource | ToCamel | FirstLower}}Client) {{template "methodDefine" $v}} {
	{{if or $v.IsStreamServer $v.IsStreamClient}}request := x.client.Verb("{{$v.Method}}").
		SubPath(
			"{{$v.URL}}",{{range $p := $v.PathParams}}
			restc.PathParam{Name: "{{$p.Name}}", Value: param.{{$p.GoName}}},{{end}}
		)
	return request, nil{{else}}var resp {{$v.Response.FullName}}
		err := x.client.Verb("{{$v.Method}}").
		Path(
			"{{$v.URL}}",{{range $p := $v.PathParams}}
			restc.PathParam{Name: "{{$p.Name}}", Value: param.{{$p.GoName}}},{{end}}
		).
		Params({{if eq $v.Request.Body "*"}}{{else}}{{range $q := $v.QueryParams}}
			restc.QueryParam{Name: "{{$q.Name}}", Value: param.{{$q.GoName}}},{{end}}{{end}}
		).
		{{ if or (eq $v.Method "GET") (eq $v.Method "DELETE") }}{{else}}Body({{if eq $v.Request.Body ""}}nil{{else if eq $v.Request.Body "*"}}param{{else if or (ne $v.Method "GET") (ne $v.Method "DELETE")}}param.{{$v.Request.RealBodyName}}{{else}}nil{{end}}).{{end}}
		Do(ctx).
		Into(&resp, &restc.IntoOptions{
            WrapCodeMsg: {{$v.WrapCodeMsg}},
		})

	if err != nil {
		return nil, err
	}

	return resp, nil{{end}}
}
{{end}}