// Code generated by goctl. DO NOT EDIT.
// Source: machine.proto

package server

import (
	"context"

	"github.com/jzero-io/jzero/app/internal/logic/machine"
	"github.com/jzero-io/jzero/app/internal/pb/machinepb"
	"github.com/jzero-io/jzero/app/internal/svc"
)

type Machine struct {
	svcCtx *svc.ServiceContext
	machinepb.UnimplementedMachineServer
}

func NewMachine(svcCtx *svc.ServiceContext) *Machine {
	return &Machine{
		svcCtx: svcCtx,
	}
}

func (s *Machine) MachineVersion(ctx context.Context, in *machinepb.Empty) (*machinepb.MachineVersionResponse, error) {
	l := machinelogic.NewMachineVersion(ctx, s.svcCtx)
	return l.MachineVersion(in)
}

func (s *Machine) Create(ctx context.Context, in *machinepb.Empty) (*machinepb.Empty, error) {
	l := machinelogic.NewCreate(ctx, s.svcCtx)
	return l.Create(in)
}
