// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	credentialapi "github.com/jaronnie/worktab/worktabd/internal/handler/credentialapi"
	machineapi "github.com/jaronnie/worktab/worktabd/internal/handler/machineapi"
	"github.com/jaronnie/worktab/worktabd/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/credential/:name",
				Handler: credentialapi.CredentialNameHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/machine/:name",
				Handler: machineapi.MachineNameHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
