// Code generated by goctl. DO NOT EDIT.
package types

type DownloadRequest struct {
	File string `path:"file"`
}

type UploadResponse struct {
	Code int `json:"code"`
}

type Request struct {
	Name string `path:"name"`
}

type Response struct {
	Message string
}
