// Code generated by goctl. DO NOT EDIT.
package types

type DownloadRequest struct {
	File string `path:"file"`
}

type UploadResponse struct {
	Code int `json:"code"`
}

type CredentialRequest struct {
	Name string `path:"name"`
}

type CredentialResponse struct {
	Message string
}

type ParamRequest struct {
	Name string `form:"name"`
}

type PathRequest struct {
	Name string `path:"name"`
}

type PostRequest struct {
	Name string `json:"name"`
}

type Response struct {
	Message string
}
