// Code generated by goctl. DO NOT EDIT.
// Source: worktabd.proto

package server

import (
	"context"

	"github.com/jaronnie/worktab/worktabd/internal/logic"
	"github.com/jaronnie/worktab/worktabd/internal/svc"
	"github.com/jaronnie/worktab/worktabd/worktabdpb"
)

type WorktabdServer struct {
	svcCtx *svc.ServiceContext
	worktabdpb.UnimplementedWorktabdServer
}

func NewWorktabdServer(svcCtx *svc.ServiceContext) *WorktabdServer {
	return &WorktabdServer{
		svcCtx: svcCtx,
	}
}

func (s *WorktabdServer) ServerVersion(ctx context.Context, in *worktabdpb.Empty) (*worktabdpb.ServerVersionResponse, error) {
	l := logic.NewServerVersionLogic(ctx, s.svcCtx)
	return l.ServerVersion(in)
}

func (s *WorktabdServer) Container(ctx context.Context, in *worktabdpb.Empty) (*worktabdpb.Container, error) {
	l := logic.NewContainerLogic(ctx, s.svcCtx)
	return l.Container(in)
}
