// Code generated by jzero. DO NOT EDIT.
// type: {{.Scope | lower}}_client

package {{.Scope | lower}}

import (
	"github.com/jzero-io/restc"
)

type {{.Scope | FirstUpper | ToCamel}}Interface interface {
	RESTClient() restc.Interface
	
	{{range $v := .Resources}}{{$v | FirstUpper| ToCamel}}Getter
	{{end}}
}

type {{.Scope | FirstUpper| ToCamel}}Client struct {
	restClient restc.Interface
}

func (x *{{.Scope | FirstUpper| ToCamel}}Client) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

{{range $v := .Resources}}func (x *{{$.Scope | FirstUpper| ToCamel}}Client) {{$v | FirstUpper| ToCamel}}() {{$v | FirstUpper| ToCamel}}Interface {
	return new{{$v | FirstUpper}}Client(x)
}

{{end}}
// NewForConfig creates a new {{.Scope | FirstUpper| ToCamel}}Client for the given config.
func NewForConfig(x *restc.RESTClient) (*{{.Scope | FirstUpper| ToCamel}}Client, error) {
	return &{{.Scope | FirstUpper| ToCamel}}Client{x}, nil
}