// Code generated by jzero. DO NOT EDIT.
// type: {{.Scope}}_client

package {{.Scope}}

import (
	"github.com/jzero-io/restc"
)

type {{.Scope | FirstUpper}}Interface interface {
	RESTClient() restc.Interface
	
	{{range $v := .Resources}}{{$v | FirstUpper}}Getter
	{{end}}
}

type {{.Scope | FirstUpper}}Client struct {
	restClient restc.Interface
}

func (x *{{.Scope | FirstUpper}}Client) RESTClient() restc.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

{{range $v := .Resources}}func (x *{{$.Scope | FirstUpper}}Client) {{$v | FirstUpper}}() {{$v | FirstUpper}}Interface {
	return new{{$v | FirstUpper}}Client(x)
}

{{end}}
// NewForConfig creates a new {{.Scope | FirstUpper}}Client for the given config.
func NewForConfig(x *restc.RESTClient) (*{{.Scope | FirstUpper}}Client, error) {
	return &{{.Scope | FirstUpper}}Client{x}, nil
}