// Code generated by goctl-types plugin. DO NOT EDIT.
package types

import (
	"time"
)

var (
	_ = time.Now()
)

type DownloadRequest struct {
	File string `path:"file"`
}

type UploadResponse struct {
	Code int `json:"code"`
}
