// Code generated by jzero. DO NOT EDIT.

package model

import (
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/jzero-io/jzero/core/stores/modelx"
    "github.com/eddieowens/opts"

	{{range $v := .Imports}}"{{$v}}"
	{{end}}
)

{{range $k,$v := .MutiModels}} type {{$k | FirstUpper | ToCamel}}Model struct {
    {{range $vv := $v}}{{$vv | FirstUpper | ToCamel}} {{$vv}}.{{$vv | FirstUpper |ToCamel}}Model
    {{end}}
}
{{end}}

type Model struct {
    {{range $v := .TablePackages}}{{$v | FirstUpper | ToCamel}} {{$v}}.{{$v | FirstUpper |ToCamel}}Model
    {{end}}
}

func NewModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) Model {
	return Model{
         {{range $v := .TablePackages}}{{$v | FirstUpper | ToCamel}}: {{$v}}.New{{ $v | FirstUpper | ToCamel }}Model(conn, op...),
         {{end}}
	}
}

{{range $k,$v := .MutiModels}} func New{{$k | FirstUpper | ToCamel}}Model(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) {{$k | FirstUpper | ToCamel}}Model {
	return {{$k | FirstUpper | ToCamel}}Model{
        {{range $vv := $v}}{{$vv | FirstUpper | ToCamel}}: {{$vv}}.New{{ $vv | FirstUpper | ToCamel }}Model(conn, op...),
        {{end}}
	}
}
{{end}}
