// Code generated by jzero. DO NOT EDIT.
// type: fake_credential

package fake

import (
	"context"

	

	"github.com/jzero-io/jzero-go/model/jzero/pb/credentialpb"
	
)

var (
	FakeReturnCredentialVersion = &credentialpb.CredentialVersionResponse{}
	FakeReturnCreateCredential = &credentialpb.CreateCredentialResponse{}
	FakeReturnCredentialList = &credentialpb.CredentialListResponse{}
	FakeReturnCredentialDetail = &credentialpb.Credential{}
	
)

type CredentialGetter interface {
	Credential() CredentialInterface

	FakeCredentialExpansion
}

type CredentialInterface interface {
	CredentialVersion(ctx context.Context, param *credentialpb.Empty) (*credentialpb.CredentialVersionResponse, error)
	CreateCredential(ctx context.Context, param *credentialpb.CreateCredentialRequest) (*credentialpb.CreateCredentialResponse, error)
	CredentialList(ctx context.Context, param *credentialpb.CredentialListRequest) (*credentialpb.CredentialListResponse, error)
	CredentialDetail(ctx context.Context, param *credentialpb.Int32Id) (*credentialpb.Credential, error)
	
}

type FakeCredential struct {
	Fake *FakeJzero
}

func (f *FakeCredential) CredentialVersion(ctx context.Context,param *credentialpb.Empty) (*credentialpb.CredentialVersionResponse, error) {
	return FakeReturnCredentialVersion, nil
}

func (f *FakeCredential) CreateCredential(ctx context.Context,param *credentialpb.CreateCredentialRequest) (*credentialpb.CreateCredentialResponse, error) {
	return FakeReturnCreateCredential, nil
}

func (f *FakeCredential) CredentialList(ctx context.Context,param *credentialpb.CredentialListRequest) (*credentialpb.CredentialListResponse, error) {
	return FakeReturnCredentialList, nil
}

func (f *FakeCredential) CredentialDetail(ctx context.Context,param *credentialpb.Int32Id) (*credentialpb.Credential, error) {
	return FakeReturnCredentialDetail, nil
}

