// Code generated by jzero. DO NOT EDIT.
// type: fake_machine

package fake

import (
	"context"

	

	"github.com/jzero-io/jzero-go/model/jzero/pb/machinepb"
	
)

var (
	FakeReturnMachineVersion = &machinepb.MachineVersionResponse{}
	
)

type MachineGetter interface {
	Machine() MachineInterface

	FakeMachineExpansion
}

type MachineInterface interface {
	MachineVersion(ctx context.Context, param *machinepb.Empty) (*machinepb.MachineVersionResponse, error)
	
}

type FakeMachine struct {
	Fake *FakeJzero
}

func (f *FakeMachine) MachineVersion(ctx context.Context,param *machinepb.Empty) (*machinepb.MachineVersionResponse, error) {
	return FakeReturnMachineVersion, nil
}

