// Code generated by jzero. DO NOT EDIT.
// type: fake_jzero_client

package fake

import (
	"github.com/jaronnie/jzero-go/rest"
	"github.com/jaronnie/jzero-go/typed/jzero"
)

type FakeJzero struct {}

func (f *FakeJzero) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}

func (f *FakeJzero) Machine() jzero.MachineInterface {
	return &FakeMachine{Fake: f}
}

func (f *FakeJzero) Hello() jzero.HelloInterface {
	return &FakeHello{Fake: f}
}

func (f *FakeJzero) Credential() jzero.CredentialInterface {
	return &FakeCredential{Fake: f}
}

