// Code generated by goctl. DO NOT EDIT.
// Source: credential.proto

package server

import (
	"context"

	"github.com/jzero-io/jzero/app/internal/logic/credential"
	"github.com/jzero-io/jzero/app/internal/pb/credentialpb"
	"github.com/jzero-io/jzero/app/internal/svc"
)

type Credential struct {
	svcCtx *svc.ServiceContext
	credentialpb.UnimplementedCredentialServer
}

func NewCredential(svcCtx *svc.ServiceContext) *Credential {
	return &Credential{
		svcCtx: svcCtx,
	}
}

func (s *Credential) CredentialVersion(ctx context.Context, in *credentialpb.Empty) (*credentialpb.CredentialVersionResponse, error) {
	l := credentiallogic.NewCredentialVersion(ctx, s.svcCtx)
	return l.CredentialVersion(in)
}

func (s *Credential) CreateCredential(ctx context.Context, in *credentialpb.CreateCredentialRequest) (*credentialpb.CreateCredentialResponse, error) {
	l := credentiallogic.NewCreateCredential(ctx, s.svcCtx)
	return l.CreateCredential(in)
}

func (s *Credential) CredentialList(ctx context.Context, in *credentialpb.CredentialListRequest) (*credentialpb.CredentialListResponse, error) {
	l := credentiallogic.NewCredentialList(ctx, s.svcCtx)
	return l.CredentialList(in)
}

func (s *Credential) CredentialDetail(ctx context.Context, in *credentialpb.Int32Id) (*credentialpb.Credential, error) {
	l := credentiallogic.NewCredentialDetail(ctx, s.svcCtx)
	return l.CredentialDetail(in)
}
