// Code generated by jzero. DO NOT EDIT.
// type: direct_client

package typed

import (
	"github.com/jzero-io/jzero-go/rest"
)


type DirectInterface interface {
	RESTClient() rest.Interface
}

type DirectClient struct {
	restClient rest.Interface
}

func (x *DirectClient) RESTClient() rest.Interface {
	if x == nil {
		return nil
	}
	return x.restClient
}

// NewForConfig creates a new DirectClient for the given config.
func NewForConfig(x *rest.RESTClient) (*DirectClient, error) {
	config := *x
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &DirectClient{client}, nil
}