// Code generated by jzero. DO NOT EDIT.

package model

import (
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/jzero-io/jzero/core/stores/modelx"
    "github.com/eddieowens/opts"

	{{range $v := .Imports}}"{{$v}}"
	{{end}}
)

type Model struct {
    {{range $v := .TablePackages}}{{$v | FirstUpper | ToCamel}} {{$v}}.{{$v | FirstUpper |ToCamel}}Model
    {{end}}
}

func NewModel(conn sqlx.SqlConn, op ...opts.Opt[modelx.ModelOpts]) Model {
	return Model{
         {{range $v := .TablePackages}}{{$v | FirstUpper | ToCamel}}: {{$v}}.New{{ $v | FirstUpper | ToCamel }}Model(conn, op...),
         {{end}}
	}
}