// Code generated by jzero. DO NOT EDIT.
// type: fake_clientset

package fake

import (
	"{{.GoModule}}/typed"
	"{{.GoModule}}/typed/fake"

{{range $k, $v := .ScopeVersions}}{{$k}} "{{$.GoModule}}/typed/{{$k}}"
fake{{$k}} "{{$.GoModule}}/typed/{{$k}}/fake"
{{end}}
)

type Clientset struct {}

func (f *Clientset) Direct() typed.DirectInterface {
	return &fake.FakeDirect{}
}

{{range $k, $v := .ScopeVersions}}func (f *Clientset) {{$v}}() {{$k}}.{{$v}}Interface {
return &fake{{$k}}.Fake{{$v}}{}
}

{{end}}