// Code generated by jzero. DO NOT EDIT.

package model

import (
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	{{if .withCache}}"github.com/zeromicro/go-zero/core/stores/cache"{{end}}

	{{range $v := .Imports}}"{{$v}}"
	{{end}}
)

type Model struct {
    {{range $v := .TablePackages}}{{$v | FirstUpper | ToCamel}} {{$v}}.{{$v | FirstUpper |ToCamel}}Model
    {{end}}
}

func NewModel(conn sqlx.SqlConn, {{if .withCache}}c cache.CacheConf, opts ...cache.Option{{end}}) Model {
	return Model{
         {{range $v := .TablePackages}}{{$v | FirstUpper | ToCamel}}: {{$v}}.New{{ $v | FirstUpper | ToCamel }}Model(conn, {{if $.withCache}}c, opts...{{end}}),
         {{end}}
	}
}