// Code generated by jzero. DO NOT EDIT.
// type: fake_direct_client

package fake

import (
	"github.com/jzero-io/jzero-go/rest"
)

type FakeDirect struct {}

func (f *FakeDirect) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}