// Code generated by jzero. DO NOT EDIT.
// type: fake_clientset

package fake

import (
	"{{.Module}}/typed"
	"{{.Module}}/typed/fake"

{{range $v := .Scopes}}    {{$v}} "{{$.Module}}/typed/{{$v}}"
    fake{{$v}} "{{$.Module}}/typed/{{$v}}/fake"
{{end}}
)

type Clientset struct {}

func (f *Clientset) Direct() typed.DirectInterface {
	return &fake.FakeDirect{}
}

{{range $v := .Scopes}}func (f *Clientset) {{$v | FirstUpper}}() {{$v}}.{{$v | FirstUpper}}Interface {
    return &fake{{$v}}.Fake{{$v | FirstUpper}}{}
}

{{end}}