
// Code generated by jzero. DO NOT EDIT.
// type: credential

package jzero

import (
    "github.com/jaronnie/jzero-go/rest"
)

type CredentialGetter interface {
	Credential() CredentialInterface
}

type CredentialInterface interface {
	
	CredentialExpansion
}

type credentialClient struct {
	client rest.Interface
}

func newCredentialClient(c *JzeroClient) *credentialClient {
	return &credentialClient{
		client: c.RESTClient(),
	}
}

